In [24]:
import numpy as np

In [25]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [26]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [27]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [29]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [30]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [31]:
x @ np.ones(3)

array([ 6., 15.])

In [32]:
from numpy.linalg import inv, qr

In [33]:
X = np.random.randn(5, 5)

In [34]:
mat = X.T.dot(X)

In [35]:
inv(mat)

array([[ 0.50167409, -0.14684452, -2.11093759, -2.63787444,  0.08849248],
       [-0.14684452,  0.80558642,  4.52385404,  5.04605529, -0.38352814],
       [-2.11093759,  4.52385404, 40.97128878, 49.29832811, -3.68588282],
       [-2.63787444,  5.04605529, 49.29832811, 60.77516627, -4.5230556 ],
       [ 0.08849248, -0.38352814, -3.68588282, -4.5230556 ,  0.4937885 ]])

In [36]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.11022302e-16,  0.00000000e+00,
         0.00000000e+00,  5.55111512e-17],
       [-2.28983499e-16,  1.00000000e+00,  2.22044605e-15,
         1.15463195e-14, -1.77635684e-15],
       [-1.38777878e-16, -4.44089210e-16,  1.00000000e+00,
        -3.10862447e-15,  8.88178420e-16],
       [ 1.24900090e-16, -9.15933995e-16, -1.48769885e-14,
         1.00000000e+00,  8.88178420e-16],
       [-4.44089210e-16, -2.22044605e-16,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00]])

In [37]:
q, r = qr(mat)

In [38]:
r

array([[-4.24413798,  2.63821326, -1.21698285,  0.10813408, -6.38811418],
       [ 0.        , -5.52215845,  3.00029928, -2.05069581, -0.95769832],
       [ 0.        ,  0.        , -1.16968236,  0.92192713, -0.48845389],
       [ 0.        ,  0.        ,  0.        , -0.39136445, -5.23825868],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.17039332]])