In [2]:
import numpy as np

In [3]:
arr = np.random.randn(6)

In [4]:
arr

array([ 0.68159486,  1.13515561,  0.2752485 , -1.13705559, -0.55545535,
       -0.36804586])

In [5]:
arr.sort()

In [6]:
arr

array([-1.13705559, -0.55545535, -0.36804586,  0.2752485 ,  0.68159486,
        1.13515561])

In [7]:
arr = np.random.randn(5, 3)

In [8]:
arr

array([[-0.61010846,  0.48981485,  2.0178922 ],
       [ 0.2163629 ,  0.71647322, -0.00458524],
       [ 1.72483562,  0.10345643, -0.69717379],
       [-0.5793688 , -1.69044262,  0.09276222],
       [-0.97790907,  1.0388968 ,  1.54080076]])

In [9]:
arr.sort(1)

In [10]:
arr

array([[-0.61010846,  0.48981485,  2.0178922 ],
       [-0.00458524,  0.2163629 ,  0.71647322],
       [-0.69717379,  0.10345643,  1.72483562],
       [-1.69044262, -0.5793688 ,  0.09276222],
       [-0.97790907,  1.0388968 ,  1.54080076]])

In [11]:
large_arr = np.random.randn(1000)

In [12]:
large_arr.sort()

In [15]:
large_arr[int(0.05 * len(large_arr))]

-1.626951794884259